{"name": "test_equality_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 11\n  -10\n  +11", "trace": "def test_equality_failure():\n>       assert 10 == 11\nE       assert 10 == 11\nE         -10\nE         +11\n\ntest_failure.py:13: AssertionError"}, "start": 1573041325485, "stop": 1573041325485, "uuid": "a77098eb-9d21-4fb0-9856-34636fdfecff", "historyId": "ea68c5d180aacf82bec78cb25adf19f0", "testCaseId": "84ed8c051a94ab2d1e2bae8554228f77", "fullName": "test_failure#test_equality_failure", "labels": [{"name": "suite", "value": "test_failure"}, {"name": "host", "value": "SIVA-PC"}, {"name": "thread", "value": "8312-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_failure"}]}