{"name": "test_square_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 49 == 40\n  -49\n  +40", "trace": "def test_square_failure():\n        num=7\n>       assert 7*7 == 40\nE       assert 49 == 40\nE         -49\nE         +40\n\ntest_failure.py:10: AssertionError"}, "start": 1573041325472, "stop": 1573041325472, "uuid": "b46aeefd-dcbf-408c-9c4e-27721f50b90b", "historyId": "9c8569319bf6e2d2b1e343e91efa0584", "testCaseId": "02c0937919be5930da596eded817ab4c", "fullName": "test_failure#test_square_failure", "labels": [{"name": "suite", "value": "test_failure"}, {"name": "host", "value": "SIVA-PC"}, {"name": "thread", "value": "8312-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_failure"}]}