{"name": "test_sqrt_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5.0 == 6\n  -5.0\n  +6", "trace": "def test_sqrt_failure():\n        num=25\n>       assert math.sqrt(num) == 6\nE       assert 5.0 == 6\nE         -5.0\nE         +6\n\ntest_failure.py:6: AssertionError"}, "start": 1573041325463, "stop": 1573041325464, "uuid": "b55d0c6c-49e5-40fd-97a2-80d8947b013a", "historyId": "1b34e9c86e327df7497d69081b80b288", "testCaseId": "9b0db56fcb3cf4eb00f9927c35b29e04", "fullName": "test_failure#test_sqrt_failure", "labels": [{"name": "suite", "value": "test_failure"}, {"name": "host", "value": "SIVA-PC"}, {"name": "thread", "value": "8312-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_failure"}]}